title: YetAnotherMind
description: Как зарождаются предпочтения в языковых моделях
theme: minima
lang: ru

baseurl: "/YetAnotherMind"
url: "https://yandexdataschool.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

header_pages:
  - index.md

permalink: pretty

exclude:
  - code/
  - .gitignore
  - README.md

minima:
  skin: classic
  
show_excerpts: false
